
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cv-loadbalancer
spec:
  replicas: 2
  selector:
    matchLabels:
      name: cv-loadbalancer
  template:
    metadata:
      name: cv-loadbalancer
      labels:
        name: cv-loadbalancer
    spec:
      containers:
        - name : cv-loadbalancer
          image: tugas_docker_2/tugasku
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: cv-service-loadbalancer
spec:
  type: LoadBalancer
  selector: 
    name: cv-loadbalancer
  ports:
    - port: 80
      targetPort: 80