apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cv-nodeport
spec:
  replicas: 2
  selector:
    matchLabels:
      name: cv-nodeport
  template:
    metadata:
      name: cv-nodeport
      labels:
        name: cv-nodeport
    spec:
      containers:
        - name : cv-nodeport
          image: tugas_docker_2/tugasku
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: cv-nodeport
spec:
  type: NodePort
  selector: 
    name: cv-nodeport
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001